kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
rules:
- apiGroups:
  - ""
  - traefik.containo.us
  - extensions
  - networking.k8s.io
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
